from pathlib import Path

# Path
ROOT_FOLDER = Path(__file__).parent
FILES_DIR = ROOT_FOLDER / 'files'
WINDOW_ICON_PATH = FILES_DIR / 'calculator_icon.png'

# Sizing
MAX_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
MIN_FONT_SIZE = 18
TEXT_MARGIN = 15

# Colors
PRIMARY_COLOR = '#1e81b0'
DARKER_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#115270'